### ISSUE TITLE
WDI-SEA/css-selectors-animal-style

### ISSUE THREAD

**Issue by scottheron** [WDI-SEA/notes#27]
[Proposed Change goes here. Make a checklist if there are multiple changes.]

Issue: Styling - "make the mammals bold
                          make the birds italic

                          make the fish underlined

                          create a new unordered list add a list item for each the following plants:"

Change: add an extra line space after the first line.

**Comment by bhague1281** [comment]
This particular deliverable will probably be deprecated, since the Instagram/Airbnb deliverables provide more comprehensive practice.
